riscv: fix compatible with binutils 2.38
commit 6df2a016c0c8a3d0933ef33dd192ea6606b115e3 from linux kernel

Since binutils 2.38, default ISA spec version switch to 20191213,
in this version, original I extension be split into I, Zicsr and Zifencei.
Zicsr is csr read/write (csrr*/csrw*) instructions, and Zifencei
is fence.i instruction.
This will cause compile error like this:
    Error: unrecognized opcode `csrr a5,0xc01'
    Error: unrecognized opcode `fence.i'

This commit add code to detect new Zicsr and Zifencei extensions,
and enable it when needed.

Signed-off-by: Coelacanthus <coelacanthus@outlook.com>
Cc: Rick Chen <rick@andestech.com>
Cc: Leo <ycliang@andestech.com>

---

Tested-by: Christian Stewart <christian@paral.in>