Remove fdt_high and initrd_high for Starfive
Fix checkpatch warning about u-boot/include/configs/starfive-vic7100.h:
```
    ERROR: fdt or initrd relocation disabled at boot time
    +       "fdt_high=0xffffffffffffffff\0" \
    
    ERROR: fdt or initrd relocation disabled at boot time
    +       "initrd_high=0xffffffffffffffff\0" \
```
Further discussion of why this is not needed and the problem its presence was causing in issue #19